config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save!
      redirect_to @flat, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @flat.update(flat_params)

    if @flat.save!
      redirect_to @flat, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container" style="width: 500px;">
  <%= form_for(@flat) do |f| %>
    <div class="input-group mb-3 d-flex justify-content-between mt-3">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="input-group mb-3 d-flex justify-content-between">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
    <div class="input-group mb-3 d-flex justify-content-between">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div class="input-group mb-3 d-flex justify-content-between">
      <%= f.label :price_per_night %>
      <%= f.number_field :price_per_night %>
    </div>
    <div class="input-group mb-3 d-flex justify-content-between">
      <%= f.label :number_of_guests %>
      <%= f.number_field :number_of_guests %>
    </div>

    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container mt-3 mb-3">
  <h2>All our flats: (<%= @flats.count %>)</h2>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-sm-4 mb-4">
        <div class="card">
          <div class="card-body bg-light bg-opacity-10">
            <h2 class="card-title"><%= flat.name %></h2>
            <p class="card-text"><%= flat.address %></p>
            <p class="card-text"><i class="fas fa-euro-sign"></i> <%= "#{flat.price_per_night}" %>  <i class="fas fa-users"></i> <%= "#{flat.number_of_guests}" %></p>
          </div>
          <div class="card-body d-flex justify-content-around">
            <%= link_to "More info", flat_path(flat), class: "link link-primary" %>
            <%= link_to "Edit this flat", edit_flat_path(flat), class: "link link-warning" %>
            <%= link_to "Delete", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class: "link link-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container" style="width: 500px;">
  <%= form_for(@flat) do |f| %>
    <div class="input-group mb-3 d-flex justify-content-between mt-3">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="input-group mb-3 d-flex justify-content-between">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
    <div class="input-group mb-3 d-flex justify-content-between">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div class="input-group mb-3 d-flex justify-content-between">
      <%= f.label :price_per_night %>
      <%= f.number_field :price_per_night %>
    </div>
    <div class="input-group mb-3 d-flex justify-content-between">
      <%= f.label :number_of_guests %>
      <%= f.number_field :number_of_guests %>
    </div>

    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="card m-2 p-4 bg-light">
        <h1 class="card-title"><%= @flat.name %></h1>
        <h4 class="card-subtitle"><%= @flat.address %></h4>
      </div>
      <div class="card m-2 p-4 bg-light">
        <h1 class="card-title">A bit more about this flat...</h1>
        <h4 class="card-subtitle"><%= @flat.description %></h4>
      </div>
      <div class="card m-2 p-4 bg-light">
        <h1 class="card-title">Details</h1>
        <h4 class="card-subtitle"><i class="fas fa-euro-sign"></i> <%= "#{@flat.price_per_night}" %> <i class="fas fa-users"></i> <%= "#{@flat.number_of_guests}" %></h4>
      </div>
    </div>
    <div class="col-4">
    </div>
  </div>

  <%= link_to "back to list of flats", flats_path, class: "m-3" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
    <h1>Simple AirBnB</h1>
    <form method="get" action="/flats/new">
      <button type="submit" class="btn btn-outline-primary">Add Flat</button>
    </form>
  </nav>

  <%= yield %>

  </body>
</html>